#!/usr/bin/env python3
"""Generate golden dashboard batch outputs for parity testing.

Usage (from a venv with sae_dashboard + its deps):
    cd <SAEDashboard repo root>
    SAE_DASHBOARD_BASELINE_WORKTREE=/path/to/SAEDashboard-7886eaa \
    python tests/acceptance/generate_golden_batches.py [--family all|dense_packed|example_aligned]

Family provenance (deliberately different):

- ``dense_packed``: generated by the detached preserved-baseline worktree's
  NeuronpediaRunner (pre-PR code) on the default dense/packed prompt flow — golden
  comparisons against it are *baseline-parity* checks.
- ``example_aligned``: generated by the IN-TREE current legacy lane consuming a
  committed example-aligned (``max-prompt-pad``) prompt cache built with this repo's
  own pretokenization utilities. The preserved baseline cannot produce example-aligned
  windowing (the capability is new in this PR), and the in-tree legacy lane is the
  canonical parity reference (fully deterministic; byte-identical to the detached
  baseline where both can run). Golden comparisons against this family are therefore
  *committed-snapshot regression* checks of the example-aligned flow, not
  baseline-parity checks.

``--family all`` (the default) runs each family in a separate subprocess so the
detached-baseline import (which shadows the in-tree ``sae_dashboard`` modules) cannot
leak into the in-tree run.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
GOLDEN_BATCHES_DIR = THIS_DIR / "golden_batches"

EXAMPLE_ALIGNED_N_PROMPTS = 64
EXAMPLE_ALIGNED_CONTEXT_SIZE = 64
EXAMPLE_ALIGNED_SEED = 20260708

# Deterministic synthetic prompt vocabulary: the golden fixtures only need realistic
# token-length variety (padding coverage), not semantic content.
_SYNTHETIC_WORDS = (
    "the quick brown fox jumps over a lazy dog while seven bright stars "
    "fade behind tall mountain ridges and quiet rivers carry small wooden "
    "boats toward distant harbor towns where merchants trade copper coins "
    "for woven cloth fresh bread ripe fruit and stories about winter storms"
).split()


def _find_baseline_worktree() -> Path:
    env_path = os.environ.get("SAE_DASHBOARD_BASELINE_WORKTREE")
    if env_path:
        return Path(env_path).expanduser().resolve()
    default = Path(
        "~/.cache/huggingface/interpretune/neuronpedia/"
        "baseline_worktrees_20260518/SAEDashboard-7886eaa"
    ).expanduser()
    if default.exists():
        return default
    raise RuntimeError(
        "Set SAE_DASHBOARD_BASELINE_WORKTREE to the detached baseline worktree path."
    )


def _resolve_batch_dir(outputs_root: Path, n_batches: int) -> Path:
    subdirs = [e for e in os.listdir(str(outputs_root)) if (outputs_root / e).is_dir()]
    batch_dir = outputs_root / subdirs[0] if subdirs else outputs_root
    for i in range(n_batches):
        bp = batch_dir / f"batch-{i}.json"
        assert bp.exists(), f"Missing {bp}"
    return batch_dir


def _copy_family_outputs(batch_dir: Path, family_dir: Path, n_batches: int) -> None:
    family_dir.mkdir(parents=True, exist_ok=True)
    for i in range(n_batches):
        src = batch_dir / f"batch-{i}.json"
        shutil.copy2(src, family_dir / f"batch-{i}.json")
        print(f"  [{family_dir.name}] batch-{i}.json ({src.stat().st_size} bytes)")
    run_settings_src = batch_dir / "run_settings.json"
    if run_settings_src.exists():
        shutil.copy2(run_settings_src, family_dir / "run_settings.json")
        print(f"  [{family_dir.name}] run_settings.json")


def _run_baseline_runner(
    baseline_worktree: Path,
    output_dir: Path,
    *,
    n_features: int = 2,
    n_batches: int = 2,
) -> Path:
    """Run the detached baseline NeuronpediaRunner directly (no subprocess)."""
    if str(baseline_worktree) not in sys.path:
        sys.path.insert(0, str(baseline_worktree))

    from sae_dashboard.neuronpedia.neuronpedia_runner import (
        NeuronpediaRunner,
        NeuronpediaRunnerConfig,
    )

    cfg = NeuronpediaRunnerConfig(
        sae_set="gpt2-small-res-jb",
        sae_path="blocks.0.hook_resid_pre",
        np_set_name="res-jb",
        from_local_sae=False,
        outputs_dir=str(output_dir / "runner_output"),
        sparsity_threshold=1,
        n_prompts_total=64,
        n_features_at_a_time=n_features,
        n_prompts_in_forward_pass=16,
        start_batch=0,
        end_batch=n_batches - 1,
        use_wandb=False,
        shuffle_tokens=False,
    )

    runner = NeuronpediaRunner(cfg)
    runner.run()
    return _resolve_batch_dir(Path(cfg.outputs_dir), n_batches)


def generate_dense_packed() -> None:
    baseline_worktree = _find_baseline_worktree()
    print(f"Baseline worktree: {baseline_worktree}")
    with tempfile.TemporaryDirectory() as tmpdir:
        batch_dir = _run_baseline_runner(baseline_worktree, Path(tmpdir))
        family_dir = GOLDEN_BATCHES_DIR / "dense_packed"
        _copy_family_outputs(batch_dir, family_dir, n_batches=2)
        (family_dir / "sae_lens.json").write_text(
            json.dumps(
                {
                    "windowing_mode": "concatenate",
                    "prompt_windowing_family": "packed_legacy",
                    "effective_context_size": 128,
                    "context_size": 128,
                    "tokenizer_name": "gpt2",
                    "dataset_path": "Skylion007/openwebtext",
                    "golden_provenance": "detached-baseline-worktree",
                }
            )
        )
        print("  [dense_packed] sae_lens.json")


def _generate_example_aligned_prompt_cache(cache_dir: Path) -> None:
    """Build a small, deterministic max-prompt-pad prompt cache with in-tree utilities."""
    import torch
    from sae_lens.config import PretokenizeRunnerConfig
    from transformers import AutoTokenizer

    from sae_dashboard.neuronpedia.prompt_datasets import (
        write_pretokenized_prompt_artifacts,
    )
    from sae_dashboard.neuronpedia.prompt_pretokenization import (
        build_windowing_metadata,
        pretokenize_prompt_token_sequences,
    )

    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    if tokenizer.pad_token_id is None:
        # GPT-2 defines no pad token; example-aligned padding uses EOS (standard practice,
        # and matches how the runner pads example-aligned prompt rows).
        tokenizer.pad_token = tokenizer.eos_token
    rng = random.Random(EXAMPLE_ALIGNED_SEED)
    token_sequences = []
    for _ in range(EXAMPLE_ALIGNED_N_PROMPTS):
        n_words = rng.randint(8, 45)
        text = " ".join(rng.choice(_SYNTHETIC_WORDS) for _ in range(n_words)) + "."
        ids = tokenizer(text)["input_ids"]
        if tokenizer.bos_token_id is not None:
            ids = [tokenizer.bos_token_id] + ids
        token_sequences.append(torch.tensor(ids, dtype=torch.long))

    cfg = PretokenizeRunnerConfig(
        tokenizer_name="gpt2",
        dataset_path="synthetic-example-aligned-golden",
        context_size=EXAMPLE_ALIGNED_CONTEXT_SIZE,
        split="train",
        shuffle=False,
        save_path=str(cache_dir),
    )
    result = pretokenize_prompt_token_sequences(
        token_sequences,
        tokenizer=tokenizer,
        cfg=cfg,
        windowing_mode="max-prompt-pad",
    )
    metadata = build_windowing_metadata(result, cfg=cfg)
    write_pretokenized_prompt_artifacts(
        result.tokenized_dataset,
        metadata=metadata,
        save_to_disk_path=str(cache_dir),
        legacy_output_dir=None,
        split="train",
        force=True,
    )
    print(
        f"  [example_aligned] prompt_cache ({len(result.tokenized_dataset)} prompts, "
        f"effective_context_size={result.effective_context_size})"
    )


def generate_example_aligned() -> None:
    """Generate the example_aligned family from the IN-TREE current legacy lane."""
    from sae_dashboard.neuronpedia.neuronpedia_runner import (
        NeuronpediaRunner,
        NeuronpediaRunnerConfig,
    )

    family_dir = GOLDEN_BATCHES_DIR / "example_aligned"
    family_dir.mkdir(parents=True, exist_ok=True)
    cache_dir = family_dir / "prompt_cache"
    if cache_dir.exists():
        shutil.rmtree(cache_dir)
    _generate_example_aligned_prompt_cache(cache_dir)

    # Under max-prompt-pad the cache's effective context is the max prompt length,
    # not the configured cap; the runner requires n_tokens_in_prompt to match it.
    cache_metadata = json.loads((cache_dir / "sae_lens.json").read_text())
    effective_context_size = int(
        cache_metadata.get("effective_context_size") or EXAMPLE_ALIGNED_CONTEXT_SIZE
    )

    with tempfile.TemporaryDirectory() as tmpdir:
        cfg = NeuronpediaRunnerConfig(
            sae_set="gpt2-small-res-jb",
            sae_path="blocks.0.hook_resid_pre",
            np_set_name="res-jb",
            from_local_sae=False,
            outputs_dir=str(Path(tmpdir) / "runner_output"),
            sparsity_threshold=1,
            n_prompts_total=EXAMPLE_ALIGNED_N_PROMPTS,
            n_tokens_in_prompt=effective_context_size,
            n_features_at_a_time=2,
            n_prompts_in_forward_pass=16,
            start_batch=0,
            end_batch=1,
            use_wandb=False,
            shuffle_tokens=False,
            pretokenized_dataset_path=str(cache_dir),
        )
        runner = NeuronpediaRunner(cfg)
        runner.run()
        batch_dir = _resolve_batch_dir(Path(cfg.outputs_dir), n_batches=2)
        _copy_family_outputs(batch_dir, family_dir, n_batches=2)

    # Sanitize host-specific paths out of the committed run_settings: consumers resolve
    # the committed cache via tests/conftest._golden_prompt_cache, not this recording.
    run_settings_path = family_dir / "run_settings.json"
    if run_settings_path.exists():
        run_settings = json.loads(run_settings_path.read_text())
        for key in ("pretokenized_dataset_path", "prompt_dataset_path"):
            if run_settings.get(key):
                run_settings[key] = "golden_batches/example_aligned/prompt_cache"
        run_settings_path.write_text(json.dumps(run_settings, indent=2))

    # The family-level sae_lens.json is the cache's REAL windowing metadata.
    family_metadata = dict(cache_metadata)
    family_metadata["golden_provenance"] = "in-tree-current-legacy"
    (family_dir / "sae_lens.json").write_text(json.dumps(family_metadata))
    print("  [example_aligned] sae_lens.json (from prompt cache metadata)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--family",
        choices=("all", "dense_packed", "example_aligned"),
        default="all",
    )
    args = parser.parse_args()

    if args.family == "all":
        # Separate subprocesses: the baseline-worktree import shadows the in-tree
        # sae_dashboard modules and must not leak into the in-tree run.
        for family in ("dense_packed", "example_aligned"):
            print(f"=== Generating {family} (subprocess) ===")
            subprocess.run(
                [sys.executable, str(Path(__file__).resolve()), "--family", family],
                check=True,
            )
        print("\nGolden batches generated successfully.")
        return

    if args.family == "dense_packed":
        generate_dense_packed()
    else:
        generate_example_aligned()
    print(f"\nGolden batches generated successfully ({args.family}).")


if __name__ == "__main__":
    main()
